import Database from './server/db.js';

const db = new Database();
db.init();

const overallData = [
  {name:'Abyss',overall:85},
  {name:'Adam Cole',overall:89},
  {name:'Adam Page',overall:93},
  {name:'Adam Pearce',overall:80},
  {name:'Adelicious',overall:75},
  {name:'Aerostar',overall:81},
  {name:'AJ Lee',overall:87},
  {name:'AJ Styles',overall:88},
  {name:'Akane',overall:84},
  {name:'Akira Tozawa',overall:68},
  {name:'Alba Fyre',overall:77},
  {name:'Alberto Del Rio',overall:91},
  {name:'Aleister Black',overall:84},
  {name:'Alex Shelley',overall:80},
  {name:'Alexa Bliss',overall:87},
  {name:'Amy Owel',overall:86},
  {name:'Andrade El Idolo',overall:85},
  {name:'Andre Bravo',overall:90},
  {name:'Andre Chase',overall:73},
  {name:'Andrea Cannon',overall:87},
  {name:'Angel',overall:72},
  {name:'Angelo Dawkins',overall:78},
  {name:'Apollo Crews',overall:70},
  {name:'Arik',overall:85},
  {name:'Asuka',overall:91},
  {name:'Austin Theory',overall:82},
  {name:'Ax (Demolition)',overall:88},
  {name:'Axiom',overall:75},
  {name:'B-Fab',overall:67},
  {name:'Bad Bunny',overall:76},
  {name:'Bandido',overall:84},
  {name:'Batista',overall:89},
  {name:'Bayley',overall:89},
  {name:'Becky Lynch',overall:94},
  {name:'Berto',overall:72},
  {name:'Bianca Belair',overall:94},
  {name:'Big Bill',overall:75},
  {name:'Big E',overall:85},
  {name:'Big Show',overall:81},
  {name:'Blake Monroe',overall:78},
  {name:'Bobby',overall:76},
  {name:'Bobby Ace',overall:58},
  {name:'Bobby Fish',overall:84},
  {name:'Bobby Lashley',overall:89},
  {name:'Bobby Roode',overall:85},
  {name:'Booker T',overall:85},
  {name:'Bravo Americano',overall:76},
  {name:'Bravoo',overall:100},
  {name:'Bray Wyatt',overall:90},
  {name:'Brock Lesnar',overall:94},
  {name:'Brody K1ng',overall:88},
  {name:'Bron Breakker',overall:90},
  {name:'Bronson Reed',overall:88},
  {name:'Brooks Jensen',overall:73},
  {name:'Brutus Creed',overall:77},
  {name:'Bryan Danielson',overall:95},
  {name:'Bubba Ray Dudley',overall:85},
  {name:'Buddy Matthews',overall:85},
  {name:'Bull Nakano',overall:90},
  {name:'Buzz',overall:94},
  {name:'Candice LeRae',overall:73},
  {name:'Carly Prime',overall:68},
  {name:'Carmelo Hayes',overall:84},
  {name:'Cash Wheeler',overall:86},
  {name:'Cedric Alexander',overall:80},
  {name:'Chad Gable',overall:81},
  {name:'Channing Lorenzo',overall:74},
  {name:'Charlie Dempsey',overall:75},
  {name:'Charlotte Flair',overall:93},
  {name:'Chase',overall:64},
  {name:'Chelsea Green',overall:85},
  {name:'Chiyoko Garcia',overall:90},
  {name:'Chosen',overall:84},
  {name:'Chris Jericho',overall:90},
  {name:'Chris Sabin',overall:80},
  {name:'Christian Cage',overall:87},
  {name:'Claudio Castagnoli',overall:84},
  {name:'CM Punk',overall:94},
  {name:'Cody Rhodes',overall:95},
  {name:'Cole Quinn',overall:68},
  {name:'Crush (Demolition)',overall:87},
  {name:'Cruz Del Toro',overall:73},
  {name:'D-Von Dudley',overall:84},
  {name:'D\'Lo Brown',overall:83},
  {name:'Dakota Kai',overall:80},
  {name:'Damian Priest',overall:87},
  {name:'Danhausen',overall:78},
  {name:'Daniel Bryan',overall:92},
  {name:'Darby Allin',overall:87},
  {name:'David Finlay',overall:86},
  {name:'Dax Harwood',overall:86},
  {name:'Death',overall:99},
  {name:'Demon Finn Balor',overall:90},
  {name:'Dexter Lumis',overall:82},
  {name:'Dirty Dominik Mysterio',overall:87},
  {name:'Doink The Clown',overall:74},
  {name:'Dr Darren',overall:85},
  {name:'Dragon Lee',overall:79},
  {name:'Dralistico',overall:82},
  {name:'Drew McIntyre',overall:93},
  {name:'Dustin Rhodes',overall:86},
  {name:'Eddie Kingston',overall:75},
  {name:'Edge',overall:91},
  {name:'El Bravo',overall:85},
  {name:'El Grande Americano',overall:85},
  {name:'El Hijo del Vikingo - Ringside Pass Season 1',overall:86},
  {name:'El Mago Jr',overall:74},
  {name:'EL Ordinario',overall:73},
  {name:'El Verdugo',overall:89},
  {name:'Elayna Black',overall:79},
  {name:'Elton Prince',overall:71},
  {name:'Emily Ward',overall:85},
  {name:'Enzo Amore',overall:74},
  {name:'Eric Bischoff',overall:58},
  {name:'Erick Rowan',overall:80},
  {name:'Erik',overall:78},
  {name:'Ethan Page',overall:83},
  {name:'Eve Torres',overall:85},
  {name:'Fallon Henley',overall:78},
  {name:'Finn Bálor',overall:88},
  {name:'Flammer - Ringside Pass Season 1',overall:85},
  {name:'Gabriel Slade',overall:83},
  {name:'Galeno Del Tormento',overall:75},
  {name:'Geneva Rose',overall:70},
  {name:'Giant Gonzalez',overall:84},
  {name:'Giulia',overall:86},
  {name:'Goldberg',overall:90},
  {name:'Golddust',overall:83},
  {name:'Grayson Waller',overall:73},
  {name:'Great Khali',overall:86},
  {name:'Gunther',overall:93},
  {name:'Hank Walker',overall:77},
  {name:'Hector Flores',overall:77},
  {name:'Hijo Del Dr. Wagner Jr',overall:85},
  {name:'Hikaru Shida',overall:92},
  {name:'Hope Eternal',overall:94},
  {name:'Ilja Dragunov',overall:85},
  {name:'IShowSpeed',overall:81},
  {name:'Ivar',overall:79},
  {name:'Ivy Nile',overall:76},
  {name:'Iyo Sky',overall:93},
  {name:'Izzi Dame',overall:76},
  {name:'Jack Swagger',overall:81},
  {name:'Jacob Fatu',overall:88},
  {name:'Jacy Jayne',overall:80},
  {name:'Jade Cargill',overall:88},
  {name:'Jaida Parker',overall:77},
  {name:'Jake Bone Jones',overall:95},
  {name:'Jake Paul',overall:86},
  {name:'Jamal',overall:82},
  {name:'Jamie Hayter',overall:88},
  {name:'Jay White',overall:89},
  {name:'Jazmyn Nyx',overall:72},
  {name:'JBL',overall:89},
  {name:'JC Mateo',overall:82},
  {name:'JD McDonagh',overall:79},
  {name:'Je\'Von Evans',overall:78},
  {name:'Jee Yung',overall:97},
  {name:'Jeff Hardy',overall:93},
  {name:'Jessika Carr [Kalyx]',overall:82},
  {name:'Jey Uso',overall:91},
  {name:'Jhon Reaper',overall:85},
  {name:'Jimmy Uso',overall:86},
  {name:'Joaquin Wilde',overall:72},
  {name:'Jodie Garcia',overall:87},
  {name:'Joe Gacy',overall:82},
  {name:'Joe Hendry',overall:80},
  {name:'John Cena',overall:97},
  {name:'John Morrison',overall:85},
  {name:'Johnny Gargano',overall:76},
  {name:'Jon Moxley',overall:91},
  {name:'Jordynne Grace',overall:81},
  {name:'Josh Briggs',overall:74},
  {name:'Josie Jane',overall:74},
  {name:'Juice Robinson',overall:91},
  {name:'Julia Hart',overall:82},
  {name:'Julianne Meadow',overall:86},
  {name:'Julius Creed',overall:78},
  {name:'Junkyard Dog',overall:84},
  {name:'Justine',overall:80},
  {name:'Juventud Guerrera',overall:85},
  {name:'Kairi Sane',overall:84},
  {name:'Kalisto',overall:81},
  {name:'Kane',overall:79},
  {name:'Karmen Petrovic',overall:75},
  {name:'Kathryn Wolf',overall:75},
  {name:'Kaven Wright',overall:92},
  {name:'Kelani Jordan',overall:79},
  {name:'Kelly Kelly',overall:82},
  {name:'Ken Shamrock',overall:86},
  {name:'Kenny Omega',overall:93},
  {name:'Kevin Owens',overall:87},
  {name:'Kiana James',overall:73},
  {name:'Killer Kross',overall:84},
  {name:'Kit Wilson',overall:74},
  {name:'Kofi Kingston',overall:83},
  {name:'Konosuke Takeshita',overall:87},
  {name:'Kris Statlander',overall:85},
  {name:'Kujo',overall:92},
  {name:'Kurt Angle',overall:89},
  {name:'Kyle Fletcher',overall:82},
  {name:'Kyle O\'Reilly',overall:84},
  {name:'La Cangrejita Loca',overall:64},
  {name:'La Hiedra',overall:83},
  {name:'LA Knight',overall:89},
  {name:'La Park',overall:86},
  {name:'La Parka',overall:86},
  {name:'Lady Hiedra',overall:90},
  {name:'Lady Maravilla',overall:81},
  {name:'Lady Marvilla',overall:75},
  {name:'Laredo Kid',overall:82},
  {name:'Lash Legend',overall:81},
  {name:'Latt Jackson (Matt)',overall:88},
  {name:'Leo the Lion',overall:82},
  {name:'Lexis King',overall:74},
  {name:'Lince Dorado',overall:79},
  {name:'Lita',overall:87},
  {name:'Liv Morgan',overall:92},
  {name:'LJ',overall:88},
  {name:'Lock',overall:88},
  {name:'Logan Paul',overall:90},
  {name:'Lola Vice',overall:78},
  {name:'Luchasaurus',overall:89},
  {name:'Ludwig Kaiser',overall:77},
  {name:'Lyra Valkyria',overall:84},
  {name:'Marina Shafir',overall:80},
  {name:'Mark Henry',overall:92},
  {name:'Maryse',overall:79},
  {name:'Matt Cardona',overall:85},
  {name:'Max Roode',overall:85},
  {name:'Maxxine Dupri',overall:78},
  {name:'Megan Bayne',overall:84},
  {name:'Mercedes Mone',overall:91},
  {name:'Michelle McCool',overall:85},
  {name:'Michin',overall:82},
  {name:'Mike Savage',overall:91},
  {name:'Mike Tyson',overall:87},
  {name:'Mil Muertes',overall:85},
  {name:'Mio Jogasaki',overall:72},
  {name:'Mistico',overall:86},
  {name:'Miz',overall:80},
  {name:'MJF',overall:91},
  {name:'Montez Ford',overall:80},
  {name:'Mosh',overall:76},
  {name:'Mr. Iguana - Ringside Pass Season 1',overall:81},
  {name:'MVP',overall:82},
  {name:'Myles Borne',overall:75},
  {name:'Naomi',overall:92},
  {name:'Natalya',overall:86},
  {name:'Nathan Frazer',overall:76},
  {name:'New Jack',overall:86},
  {name:'Nia Jax',overall:88},
  {name:'Nic Nemeth',overall:87},
  {name:'Nick Aldis',overall:80},
  {name:'Nick Jackson',overall:88},
  {name:'Nikki Bella',overall:88},
  {name:'Nikki Cross',overall:73},
  {name:'Nikkita Lyons',overall:73},
  {name:'Niko Vance',overall:76},
  {name:'Noam Dar',overall:76},
  {name:'Oba Femi',overall:85},
  {name:'Octagon Jr',overall:83},
  {name:'Odyssey Rift',overall:74},
  {name:'Okada',overall:94},
  {name:'Omos',overall:80},
  {name:'Orange Casidy',overall:90},
  {name:'Original El Grande Americano',overall:85},
  {name:'Otis',overall:75},
  {name:'Pac',overall:86},
  {name:'Paige (Saraya)',overall:88},
  {name:'Paragon Jay Pierce',overall:86},
  {name:'Pat McAfee',overall:80},
  {name:'Penta',overall:84},
  {name:'Perry Saturn',overall:83},
  {name:'Pete Dunne',overall:76},
  {name:'Piper Niven',overall:79},
  {name:'Psycho Clown - Ringside Pass Season 1',overall:84},
  {name:'Psyco Sally',overall:67},
  {name:'R-Truth',overall:80},
  {name:'Raiden Yuri',overall:86},
  {name:'Randy Orton',overall:92},
  {name:'Raquel Rodriguez',overall:86},
  {name:'Raven',overall:86},
  {name:'Ravo Americano',overall:76},
  {name:'Rayo Fantasma',overall:75},
  {name:'Red',overall:93},
  {name:'Reina Dorada',overall:80},
  {name:'Réy Fenix',overall:78},
  {name:'Rey Mysterio',overall:85},
  {name:'Rhea Ripley',overall:96},
  {name:'Ricky Saints',overall:81},
  {name:'Ricky Sosa',overall:83},
  {name:'Ricochet',overall:85},
  {name:'Ridge Holland',overall:74},
  {name:'Rikishi',overall:81},
  {name:'Road Dogg',overall:80},
  {name:'Rob Van Dam',overall:90},
  {name:'Rock',overall:95},
  {name:'Roddy Piper',overall:84},
  {name:'Roman Reigns',overall:95},
  {name:'Ronda Rousey',overall:94},
  {name:'Rosey',overall:80},
  {name:'Roxanne Perez',overall:85},
  {name:'Royce Keys',overall:80},
  {name:'Rusev',overall:83},
  {name:'Ryback',overall:84},
  {name:'Sami Zayn',overall:89},
  {name:'Samoa Joe',overall:90},
  {name:'Sandman',overall:86},
  {name:'Santos Escobar',overall:76},
  {name:'Saya Kamitani',overall:86},
  {name:'Scott Hall',overall:87},
  {name:'Seth "Freakin" Rollins',overall:94},
  {name:'Shane Talyor',overall:81},
  {name:'Shawn Michaels',overall:87},
  {name:'Shawn Spears',overall:75},
  {name:'Sheamus',overall:86},
  {name:'Shinsuke Nakamura',overall:86},
  {name:'Shyvana',overall:89},
  {name:'Sin Cara',overall:81},
  {name:'Skye Blue',overall:90},
  {name:'Slade',overall:92},
  {name:'Smash (Demolition)',overall:88},
  {name:'Sol Ruca',overall:77},
  {name:'Solo Sikoa',overall:85},
  {name:'Sombra Del Rayo',overall:89},
  {name:'Stacy Keibler',overall:75},
  {name:'Stephanie McMahon',overall:75},
  {name:'Stephanie Vaquer',overall:92},
  {name:'Stone Cold Steve Austin',overall:97},
  {name:'String (Sting)',overall:92},
  {name:'Suicide',overall:79},
  {name:'Swerve',overall:91},
  {name:'Talla Tonga',overall:77},
  {name:'Tama Tonga',overall:83},
  {name:'Tank Ledger',overall:77},
  {name:'Tatum Paxley',overall:75},
  {name:'Tavion Heights',overall:76},
  {name:'Tavish',overall:76},
  {name:'Terry Funk',overall:87},
  {name:'The Fiend',overall:92},
  {name:'The Fiend Bray Wyatt',overall:92},
  {name:'The Miedo',overall:89},
  {name:'Thea Hail',overall:75},
  {name:'Thrasher',overall:76},
  {name:'Tiffany Stratton',overall:91},
  {name:'Tommaso Ciampa',overall:77},
  {name:'Tonga Loa',overall:79},
  {name:'Toni Storm',overall:95},
  {name:'Tony D\'Angelo',overall:79},
  {name:'TRE',overall:86},
  {name:'Trick Williams',overall:84},
  {name:'Triple H',overall:91},
  {name:'Trish Stratus',overall:89},
  {name:'Tyler Bate',overall:76},
  {name:'Tyler Breeze',overall:75},
  {name:'Tyson Kidd',overall:82},
  {name:'Uncle Howdy',overall:87},
  {name:'Undertaker',overall:96},
  {name:'Utami',overall:93},
  {name:'Vader',overall:87},
  {name:'Venom Miss',overall:98},
  {name:'Victoria',overall:89},
  {name:'Wade Barrett',overall:85},
  {name:'Wendy Choo',overall:72},
  {name:'Wheeler Yuta',overall:82},
  {name:'Will Ospreay',overall:88},
  {name:'William Regal',overall:76},
  {name:'Wren Sinclair',overall:74},
  {name:'Xavier Woods',overall:82},
  {name:'Yoshiki Inamura',overall:75},
  {name:'Zaria',overall:75},
  {name:'Zelina Vega',overall:83},
  {name:'Zoey Stark',overall:80},
  {name:'Evil',overall:84},
  {name:'Mason Rook',overall:83}
];

console.log('⭐ Updating wrestler overall ratings...\n');

const wrestlers = db.getAllWrestlers();
let updated = 0;
let notFound = 0;
let alreadySet = 0;

// Track top-rated wrestlers
const topRated = [];

overallData.forEach(entry => {
  const wrestler = wrestlers.find(w => 
    w.name.toLowerCase() === entry.name.toLowerCase() ||
    w.name.toLowerCase().includes(entry.name.toLowerCase()) ||
    entry.name.toLowerCase().includes(w.name.toLowerCase())
  );
  
  if (wrestler) {
    if (wrestler.overall && wrestler.overall === entry.overall) {
      alreadySet++;
      return;
    }
    
    db.updateWrestler(
      wrestler.id,
      wrestler.name,
      wrestler.show,
      wrestler.division,
      wrestler.status,
      wrestler.imageUrl,
      wrestler.gender,
      entry.overall,
      wrestler.alignment,
      wrestler.titles
    );
    
    // Track top performers
    if (entry.overall >= 95) {
      topRated.push(`${wrestler.name} (${entry.overall})`);
    }
    
    console.log(`✅ ${wrestler.name} → ${entry.overall}`);
    updated++;
  } else {
    console.log(`❌ NOT FOUND: ${entry.name}`);
    notFound++;
  }
});

console.log(`\n📊 Summary:`);
console.log(`   Updated: ${updated} wrestlers`);
console.log(`   Already set: ${alreadySet} wrestlers`);
console.log(`   Not found: ${notFound} wrestlers`);

if (topRated.length > 0) {
  console.log(`\n⭐ Elite Performers (95+ Overall):`);
  topRated.forEach(name => console.log(`   🏆 ${name}`));
}

console.log(`\n✨ Done!`);

db.close();
