import Database from './server/db.js';

const db = new Database();
db.init();

const genderData = [
  {name:'Abyss',gender:'Male'},
  {name:'Adam Cole',gender:'Male'},
  {name:'Adam Page',gender:'Male'},
  {name:'Adam Pearce',gender:'Male'},
  {name:'Adelicious',gender:'Female'},
  {name:'Aerostar',gender:'Male'},
  {name:'AJ Lee',gender:'Female'},
  {name:'AJ Styles',gender:'Male'},
  {name:'Akane',gender:'Male'},
  {name:'Akira Tozawa',gender:'Male'},
  {name:'Alba Fyre',gender:'Female'},
  {name:'Alberto Del Rio',gender:'Male'},
  {name:'Aleister Black',gender:'Male'},
  {name:'Alex Shelley',gender:'Male'},
  {name:'Alexa Bliss',gender:'Female'},
  {name:'Amy Owel',gender:'Female'},
  {name:'Andrade El Idolo',gender:'Male'},
  {name:'Andre Bravo',gender:'Male'},
  {name:'Andre Chase',gender:'Male'},
  {name:'Andrea Cannon',gender:'Female'},
  {name:'Angel',gender:'Male'},
  {name:'Angelo Dawkins',gender:'Male'},
  {name:'Apollo Crews',gender:'Male'},
  {name:'Arik',gender:'Male'},
  {name:'Asuka',gender:'Female'},
  {name:'Austin Theory',gender:'Male'},
  {name:'Ax (Demolition)',gender:'Male'},
  {name:'Axiom',gender:'Male'},
  {name:'B-Fab',gender:'Female'},
  {name:'Bad Bunny',gender:'Male'},
  {name:'Bandido',gender:'Male'},
  {name:'Batista',gender:'Male'},
  {name:'Bayley',gender:'Female'},
  {name:'Becky Lynch',gender:'Female'},
  {name:'Berto',gender:'Male'},
  {name:'Bianca Belair',gender:'Female'},
  {name:'Big Bill',gender:'Male'},
  {name:'Big E',gender:'Male'},
  {name:'Big Show',gender:'Male'},
  {name:'Blake Monroe',gender:'Female'},
  {name:'Bobby',gender:'Male'},
  {name:'Bobby Ace',gender:'Male'},
  {name:'Bobby Fish',gender:'Male'},
  {name:'Bobby Lashley',gender:'Male'},
  {name:'Bobby Roode',gender:'Male'},
  {name:'Booker T',gender:'Male'},
  {name:'Bravo Americano',gender:'Male'},
  {name:'Bravoo',gender:'Male'},
  {name:'Bray Wyatt',gender:'Male'},
  {name:'Brock Lesnar',gender:'Male'},
  {name:'Brody K1ng',gender:'Male'},
  {name:'Bron Breakker',gender:'Male'},
  {name:'Bronson Reed',gender:'Male'},
  {name:'Brooks Jensen',gender:'Male'},
  {name:'Brutus Creed',gender:'Male'},
  {name:'Bryan Danielson',gender:'Male'},
  {name:'Bubba Ray Dudley',gender:'Male'},
  {name:'Buddy Matthews',gender:'Male'},
  {name:'Bull Nakano',gender:'Female'},
  {name:'Buzz',gender:'Male'},
  {name:'Candice LeRae',gender:'Female'},
  {name:'Carly Prime',gender:'Female'},
  {name:'Carmelo Hayes',gender:'Male'},
  {name:'Cash Wheeler',gender:'Male'},
  {name:'Cedric Alexander',gender:'Male'},
  {name:'Chad Gable',gender:'Male'},
  {name:'Channing Lorenzo',gender:'Male'},
  {name:'Charlie Dempsey',gender:'Male'},
  {name:'Charlotte Flair',gender:'Female'},
  {name:'Chase',gender:'Male'},
  {name:'Chelsea Green',gender:'Female'},
  {name:'Chiyoko Garcia',gender:'Female'},
  {name:'Chosen',gender:'Male'},
  {name:'Chris Jericho',gender:'Male'},
  {name:'Chris Sabin',gender:'Male'},
  {name:'Christian Cage',gender:'Male'},
  {name:'Claudio Castagnoli',gender:'Male'},
  {name:'CM Punk',gender:'Male'},
  {name:'Cody Rhodes',gender:'Male'},
  {name:'Cole Quinn',gender:'Male'},
  {name:'Crush (Demolition)',gender:'Male'},
  {name:'Cruz Del Toro',gender:'Male'},
  {name:'D-Von Dudley',gender:'Male'},
  {name:'D\'Lo Brown',gender:'Male'},
  {name:'Dakota Kai',gender:'Female'},
  {name:'Damian Priest',gender:'Male'},
  {name:'Danhausen',gender:'Male'},
  {name:'Daniel Bryan',gender:'Male'},
  {name:'Darby Allin',gender:'Male'},
  {name:'David Finlay',gender:'Male'},
  {name:'Dax Harwood',gender:'Male'},
  {name:'Death',gender:'Male'},
  {name:'Demon Finn Balor',gender:'Male'},
  {name:'Dexter Lumis',gender:'Male'},
  {name:'Dirty Dominik Mysterio',gender:'Male'},
  {name:'Doink The Clown',gender:'Male'},
  {name:'Dr Darren',gender:'Male'},
  {name:'Dragon Lee',gender:'Male'},
  {name:'Dralistico',gender:'Male'},
  {name:'Drew McIntyre',gender:'Male'},
  {name:'Dustin Rhodes',gender:'Male'},
  {name:'Eddie Kingston',gender:'Male'},
  {name:'Edge',gender:'Male'},
  {name:'El Bravo',gender:'Male'},
  {name:'El Grande Americano',gender:'Male'},
  {name:'El Hijo del Vikingo - Ringside Pass Season 1',gender:'Male'},
  {name:'El Mago Jr',gender:'Male'},
  {name:'EL Ordinario',gender:'Male'},
  {name:'El Verdugo',gender:'Male'},
  {name:'Elayna Black',gender:'Female'},
  {name:'Elton Prince',gender:'Male'},
  {name:'Emily Ward',gender:'Female'},
  {name:'Enzo Amore',gender:'Male'},
  {name:'Eric Bischoff',gender:'Male'},
  {name:'Erick Rowan',gender:'Male'},
  {name:'Erik',gender:'Male'},
  {name:'Ethan Page',gender:'Male'},
  {name:'Eve Torres',gender:'Female'},
  {name:'Fallon Henley',gender:'Female'},
  {name:'Finn Bálor',gender:'Male'},
  {name:'Flammer - Ringside Pass Season 1',gender:'Female'},
  {name:'Gabriel Slade',gender:'Male'},
  {name:'Galeno Del Tormento',gender:'Male'},
  {name:'Geneva Rose',gender:'Female'},
  {name:'Giant Gonzalez',gender:'Male'},
  {name:'Giulia',gender:'Female'},
  {name:'Goldberg',gender:'Male'},
  {name:'Golddust',gender:'Male'},
  {name:'Grayson Waller',gender:'Male'},
  {name:'Great Khali',gender:'Male'},
  {name:'Gunther',gender:'Male'},
  {name:'Hank Walker',gender:'Male'},
  {name:'Hector Flores',gender:'Male'},
  {name:'Hijo Del Dr. Wagner Jr',gender:'Male'},
  {name:'Hikaru Shida',gender:'Female'},
  {name:'Hope Eternal',gender:'Female'},
  {name:'Ilja Dragunov',gender:'Male'},
  {name:'IShowSpeed',gender:'Male'},
  {name:'Ivar',gender:'Male'},
  {name:'Ivy Nile',gender:'Female'},
  {name:'Iyo Sky',gender:'Female'},
  {name:'Izzi Dame',gender:'Female'},
  {name:'Jack Swagger',gender:'Male'},
  {name:'Jacob Fatu',gender:'Male'},
  {name:'Jacy Jayne',gender:'Female'},
  {name:'Jade Cargill',gender:'Female'},
  {name:'Jaida Parker',gender:'Female'},
  {name:'Jake Bone Jones',gender:'Male'},
  {name:'Jake Paul',gender:'Male'},
  {name:'Jamal',gender:'Male'},
  {name:'Jamie Hayter',gender:'Female'},
  {name:'Jay White',gender:'Male'},
  {name:'Jazmyn Nyx',gender:'Female'},
  {name:'JBL',gender:'Male'},
  {name:'JC Mateo',gender:'Male'},
  {name:'JD McDonagh',gender:'Male'},
  {name:'Je\'Von Evans',gender:'Male'},
  {name:'Jee Yung',gender:'Female'},
  {name:'Jeff Hardy',gender:'Male'},
  {name:'Jessika Carr [Kalyx]',gender:'Female'},
  {name:'Jey Uso',gender:'Male'},
  {name:'Jhon Reaper',gender:'Male'},
  {name:'Jimmy Uso',gender:'Male'},
  {name:'Joaquin Wilde',gender:'Male'},
  {name:'Jodie Garcia',gender:'Female'},
  {name:'Joe Gacy',gender:'Male'},
  {name:'Joe Hendry',gender:'Male'},
  {name:'John Cena',gender:'Male'},
  {name:'John Morrison',gender:'Male'},
  {name:'Johnny Gargano',gender:'Male'},
  {name:'Jon Moxley',gender:'Male'},
  {name:'Jordynne Grace',gender:'Female'},
  {name:'Josh Briggs',gender:'Male'},
  {name:'Josie Jane',gender:'Female'},
  {name:'Juice Robinson',gender:'Male'},
  {name:'Julia Hart',gender:'Female'},
  {name:'Julianne Meadow',gender:'Female'},
  {name:'Julius Creed',gender:'Male'},
  {name:'Junkyard Dog',gender:'Male'},
  {name:'Justine',gender:'Female'},
  {name:'Juventud Guerrera',gender:'Male'},
  {name:'Kairi Sane',gender:'Female'},
  {name:'Kalisto',gender:'Male'},
  {name:'Kane',gender:'Male'},
  {name:'Karmen Petrovic',gender:'Female'},
  {name:'Kathryn Wolf',gender:'Female'},
  {name:'Kaven Wright',gender:'Male'},
  {name:'Kelani Jordan',gender:'Female'},
  {name:'Kelly Kelly',gender:'Female'},
  {name:'Ken Shamrock',gender:'Male'},
  {name:'Kenny Omega',gender:'Male'},
  {name:'Kevin Owens',gender:'Male'},
  {name:'Kiana James',gender:'Female'},
  {name:'Killer Kross',gender:'Male'},
  {name:'Kit Wilson',gender:'Male'},
  {name:'Kofi Kingston',gender:'Male'},
  {name:'Konosuke Takeshita',gender:'Male'},
  {name:'Kris Statlander',gender:'Female'},
  {name:'Kujo',gender:'Female'},
  {name:'Kurt Angle',gender:'Male'},
  {name:'Kyle Fletcher',gender:'Male'},
  {name:'Kyle O\'Reilly',gender:'Male'},
  {name:'La Cangrejita Loca',gender:'Female'},
  {name:'La Hiedra',gender:'Female'},
  {name:'LA Knight',gender:'Male'},
  {name:'La Park',gender:'Male'},
  {name:'La Parka',gender:'Male'},
  {name:'Lady Hiedra',gender:'Female'},
  {name:'Lady Maravilla',gender:'Female'},
  {name:'Lady Marvilla',gender:'Female'},
  {name:'Laredo Kid',gender:'Male'},
  {name:'Lash Legend',gender:'Female'},
  {name:'Latt Jackson (Matt)',gender:'Male'},
  {name:'Leo the Lion',gender:'Male'},
  {name:'Lexis King',gender:'Male'},
  {name:'Lince Dorado',gender:'Male'},
  {name:'Lita',gender:'Female'},
  {name:'Liv Morgan',gender:'Female'},
  {name:'LJ',gender:'Female'},
  {name:'Lock',gender:'Male'},
  {name:'Logan Paul',gender:'Male'},
  {name:'Lola Vice',gender:'Female'},
  {name:'Luchasaurus',gender:'Male'},
  {name:'Ludwig Kaiser',gender:'Male'},
  {name:'Lyra Valkyria',gender:'Female'},
  {name:'Marina Shafir',gender:'Female'},
  {name:'Mark Henry',gender:'Male'},
  {name:'Maryse',gender:'Female'},
  {name:'Matt Cardona',gender:'Male'},
  {name:'Max Roode',gender:'Male'},
  {name:'Maxxine Dupri',gender:'Female'},
  {name:'Megan Bayne',gender:'Female'},
  {name:'Mercedes Mone',gender:'Female'},
  {name:'Michelle McCool',gender:'Female'},
  {name:'Michin',gender:'Female'},
  {name:'Mike Savage',gender:'Male'},
  {name:'Mike Tyson',gender:'Male'},
  {name:'Mil Muertes',gender:'Male'},
  {name:'Mio Jogasaki',gender:'Female'},
  {name:'Mistico',gender:'Male'},
  {name:'Miz',gender:'Male'},
  {name:'MJF',gender:'Male'},
  {name:'Montez Ford',gender:'Male'},
  {name:'Mosh',gender:'Male'},
  {name:'Mr. Iguana - Ringside Pass Season 1',gender:'Male'},
  {name:'MVP',gender:'Male'},
  {name:'Myles Borne',gender:'Male'},
  {name:'Naomi',gender:'Female'},
  {name:'Natalya',gender:'Female'},
  {name:'Nathan Frazer',gender:'Male'},
  {name:'New Jack',gender:'Male'},
  {name:'Nia Jax',gender:'Female'},
  {name:'Nic Nemeth',gender:'Male'},
  {name:'Nick Aldis',gender:'Male'},
  {name:'Nick Jackson',gender:'Male'},
  {name:'Nikki Bella',gender:'Female'},
  {name:'Nikki Cross',gender:'Female'},
  {name:'Nikkita Lyons',gender:'Female'},
  {name:'Niko Vance',gender:'Male'},
  {name:'Noam Dar',gender:'Male'},
  {name:'Oba Femi',gender:'Male'},
  {name:'Octagon Jr',gender:'Male'},
  {name:'Odyssey Rift',gender:'Female'},
  {name:'Okada',gender:'Male'},
  {name:'Omos',gender:'Male'},
  {name:'Orange Casidy',gender:'Male'},
  {name:'Original El Grande Americano',gender:'Male'},
  {name:'Otis',gender:'Male'},
  {name:'Pac',gender:'Male'},
  {name:'Paige (Saraya)',gender:'Female'},
  {name:'Paragon Jay Pierce',gender:'Male'},
  {name:'Pat McAfee',gender:'Male'},
  {name:'Penta',gender:'Male'},
  {name:'Perry Saturn',gender:'Male'},
  {name:'Pete Dunne',gender:'Male'},
  {name:'Piper Niven',gender:'Female'},
  {name:'Psycho Clown - Ringside Pass Season 1',gender:'Male'},
  {name:'Psyco Sally',gender:'Female'},
  {name:'R-Truth',gender:'Male'},
  {name:'Raiden Yuri',gender:'Female'},
  {name:'Randy Orton',gender:'Male'},
  {name:'Raquel Rodriguez',gender:'Female'},
  {name:'Raven',gender:'Male'},
  {name:'Ravo Americano',gender:'Male'},
  {name:'Rayo Fantasma',gender:'Male'},
  {name:'Red',gender:'Female'},
  {name:'Reina Dorada',gender:'Female'},
  {name:'Réy Fenix',gender:'Male'},
  {name:'Rey Mysterio',gender:'Male'},
  {name:'Rhea Ripley',gender:'Female'},
  {name:'Ricky Saints',gender:'Male'},
  {name:'Ricky Sosa',gender:'Male'},
  {name:'Ricochet',gender:'Male'},
  {name:'Ridge Holland',gender:'Male'},
  {name:'Rikishi',gender:'Male'},
  {name:'Road Dogg',gender:'Male'},
  {name:'Rob Van Dam',gender:'Male'},
  {name:'Rock',gender:'Male'},
  {name:'Roddy Piper',gender:'Male'},
  {name:'Roman Reigns',gender:'Male'},
  {name:'Ronda Rousey',gender:'Female'},
  {name:'Rosey',gender:'Male'},
  {name:'Roxanne Perez',gender:'Female'},
  {name:'Royce Keys',gender:'Male'},
  {name:'Rusev',gender:'Male'},
  {name:'Ryback',gender:'Male'},
  {name:'Sami Zayn',gender:'Male'},
  {name:'Samoa Joe',gender:'Male'},
  {name:'Sandman',gender:'Male'},
  {name:'Santos Escobar',gender:'Male'},
  {name:'Saya Kamitani',gender:'Female'},
  {name:'Scott Hall',gender:'Male'},
  {name:'Seth "Freakin" Rollins',gender:'Male'},
  {name:'Shane Talyor',gender:'Male'},
  {name:'Shawn Michaels',gender:'Male'},
  {name:'Shawn Spears',gender:'Male'},
  {name:'Sheamus',gender:'Male'},
  {name:'Shinsuke Nakamura',gender:'Male'},
  {name:'Shyvana',gender:'Female'},
  {name:'Sin Cara',gender:'Male'},
  {name:'Skye Blue',gender:'Female'},
  {name:'Slade',gender:'Male'},
  {name:'Smash (Demolition)',gender:'Male'},
  {name:'Sol Ruca',gender:'Female'},
  {name:'Solo Sikoa',gender:'Male'},
  {name:'Sombra Del Rayo',gender:'Male'},
  {name:'Stacy Keibler',gender:'Female'},
  {name:'Stephanie McMahon',gender:'Female'},
  {name:'Stephanie Vaquer',gender:'Female'},
  {name:'Stone Cold Steve Austin',gender:'Male'},
  {name:'String (Sting)',gender:'Male'},
  {name:'Suicide',gender:'Male'},
  {name:'Swerve',gender:'Male'},
  {name:'Talla Tonga',gender:'Male'},
  {name:'Tama Tonga',gender:'Male'},
  {name:'Tank Ledger',gender:'Male'},
  {name:'Tatum Paxley',gender:'Female'},
  {name:'Tavion Heights',gender:'Male'},
  {name:'Tavish',gender:'Male'},
  {name:'Terry Funk',gender:'Male'},
  {name:'The Fiend',gender:'Male'},
  {name:'The Fiend Bray Wyatt',gender:'Male'},
  {name:'The Miedo',gender:'Male'},
  {name:'Thea Hail',gender:'Female'},
  {name:'Thrasher',gender:'Male'},
  {name:'Tiffany Stratton',gender:'Female'},
  {name:'Tommaso Ciampa',gender:'Male'},
  {name:'Tonga Loa',gender:'Male'},
  {name:'Toni Storm',gender:'Female'},
  {name:'Tony D\'Angelo',gender:'Male'},
  {name:'TRE',gender:'Male'},
  {name:'Trick Williams',gender:'Male'},
  {name:'Triple H',gender:'Male'},
  {name:'Trish Stratus',gender:'Female'},
  {name:'Tyler Bate',gender:'Male'},
  {name:'Tyler Breeze',gender:'Male'},
  {name:'Tyson Kidd',gender:'Male'},
  {name:'Uncle Howdy',gender:'Male'},
  {name:'Undertaker',gender:'Male'},
  {name:'Utami',gender:'Female'},
  {name:'Vader',gender:'Male'},
  {name:'Venom Miss',gender:'Female'},
  {name:'Victoria',gender:'Female'},
  {name:'Wade Barrett',gender:'Male'},
  {name:'Wendy Choo',gender:'Female'},
  {name:'Wheeler Yuta',gender:'Male'},
  {name:'Will Ospreay',gender:'Male'},
  {name:'William Regal',gender:'Male'},
  {name:'Wren Sinclair',gender:'Female'},
  {name:'Xavier Woods',gender:'Male'},
  {name:'Yoshiki Inamura',gender:'Male'},
  {name:'Zaria',gender:'Female'},
  {name:'Zelina Vega',gender:'Female'},
  {name:'Zoey Stark',gender:'Female'},
  {name:'Evil',gender:'Male'},
  {name:'Mason Rook',gender:'Male'}
];

console.log('👤 Updating wrestler genders...\n');

const wrestlers = db.getAllWrestlers();
let updated = 0;
let notFound = 0;
let alreadySet = 0;

genderData.forEach(entry => {
  const wrestler = wrestlers.find(w => 
    w.name.toLowerCase() === entry.name.toLowerCase() ||
    w.name.toLowerCase().includes(entry.name.toLowerCase()) ||
    entry.name.toLowerCase().includes(w.name.toLowerCase())
  );
  
  if (wrestler) {
    if (wrestler.gender && wrestler.gender === entry.gender) {
      alreadySet++;
      return;
    }
    
    db.updateWrestler(
      wrestler.id,
      wrestler.name,
      wrestler.show,
      wrestler.division,
      wrestler.status,
      wrestler.imageUrl,
      entry.gender,
      wrestler.overall,
      wrestler.alignment,
      wrestler.titles
    );
    console.log(`✅ ${wrestler.name} → ${entry.gender}`);
    updated++;
  } else {
    console.log(`❌ NOT FOUND: ${entry.name}`);
    notFound++;
  }
});

console.log(`\n📊 Summary:`);
console.log(`   Updated: ${updated} wrestlers`);
console.log(`   Already set: ${alreadySet} wrestlers`);
console.log(`   Not found: ${notFound} wrestlers`);
console.log(`\n✨ Done!`);

db.close();
